### ISSUE TITLE
[BUG] No longer seems to compile

### ISSUE THREAD

**Issue by VisLab** [NeurodataWithoutBorders/ndx-labmetadata-example#3]
Something is out of date here.  Running the `create_extension_spec` fails with the following message. The same message occurs when directly running the tests.

```
H:\NWBPython\ndx-labmetadata-example\venv\Scripts\python.exe H:\NWBPython\ndx-labmetadata-example\src\spec\create_extension_spec.py 
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "H:\NWBPython\ndx-labmetadata-example\src\spec\create_extension_spec.py", line 4, in <module>
    from pynwb.spec import NWBNamespaceBuilder, export_spec, NWBGroupSpec
  File "H:\NWBPython\ndx-labmetadata-example\venv\lib\site-packages\pynwb\__init__.py", line 16, in <module>
    import hdmf.common
  File "H:\NWBPython\ndx-labmetadata-example\venv\lib\site-packages\hdmf\common\__init__.py", line 128, in <module>
    from . import sparse  # noqa: F401,E402
  File "H:\NWBPython\ndx-labmetadata-example\venv\lib\site-packages\hdmf\common\sparse.py", line 3, in <module>
    import scipy.sparse as sps
  File "H:\NWBPython\ndx-labmetadata-example\venv\lib\site-packages\scipy\sparse\__init__.py", line 274, in <module>
    from ._csr import *
  File "H:\NWBPython\ndx-labmetadata-example\venv\lib\site-packages\scipy\sparse\_csr.py", line 11, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: numpy.core.multiarray failed to import

```

**Comment by oruebel** [comment]
This looks like the version of numpy you are using may have changed. I would try to update or reinstall PyNWB, e.g., via `pip install pynwb --upgrade`

**Comment by VisLab** [comment]
I had upgraded pynwb to the latest version before -- but that didn't help.  I directly upgraded numpy to the latest version and that fixed the problem. Thx!

**Comment by oruebel** [comment]
Glad upgrading numpy fixed the problem 👍
